# Generated by Django 3.2.18 on 2023-03-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='exercises',
            field=models.ManyToManyField(blank=True, through='routines.BlockExercise', to='routines.Exercise'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='days_of_week',
            field=models.ManyToManyField(blank=True, through='routines.RoutineDaysBlocks', to='routines.Day'),
        ),
    ]
