# Generated by Django 3.2.18 on 2023-03-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0002_auto_20230304_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockexercise',
            name='pause',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='blockexercise',
            name='weight',
            field=models.CharField(max_length=50),
        ),
    ]
