# Generated by Django 3.2.18 on 2023-04-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0003_auto_20230304_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='days_of_week',
            field=models.ManyToManyField(blank=True, related_name='blocks', through='routines.RoutineDaysBlocks', to='routines.Day'),
        ),
    ]
