# Generated by Django 3.2.19 on 2023-07-07 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Customer status',
                'verbose_name_plural': 'Customer status',
            },
        ),
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerTypeLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('translation', models.CharField(max_length=150)),
                ('customer_type', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='customers.customertype')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.language')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customertype',
            name='lang',
            field=models.ManyToManyField(blank=True, through='customers.CustomerTypeLang', to='main.Language'),
        ),
        migrations.CreateModel(
            name='CustomerStatusLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('translation', models.CharField(max_length=150)),
                ('customer_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.customerstatus')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.language')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customerstatus',
            name='lang',
            field=models.ManyToManyField(blank=True, through='customers.CustomerStatusLang', to='main.Language'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('username', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=200)),
                ('customer_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='customers.customertype')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='customers.customerstatus')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
