# Generated by Django 3.2.19 on 2023-07-07 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routines', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contact_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='routines.contacttype'),
        ),
        migrations.AddField(
            model_name='customer',
            name='goals',
            field=models.ManyToManyField(blank=True, to='routines.Goal'),
        ),
        migrations.AddField(
            model_name='customer',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='routines.level'),
        ),
        migrations.AddField(
            model_name='customer',
            name='restrictions',
            field=models.ManyToManyField(blank=True, to='routines.Restriction'),
        ),
        migrations.AddField(
            model_name='customer',
            name='routines',
            field=models.ManyToManyField(blank=True, through='routines.RoutineCustomers', to='routines.Routine'),
        ),
        migrations.AddField(
            model_name='customer',
            name='trainings_preferences',
            field=models.ManyToManyField(blank=True, to='routines.Training'),
        ),
    ]
