# Generated by Django 3.2.19 on 2023-07-07 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlockStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Block status',
                'verbose_name_plural': 'Block status',
            },
        ),
        migrations.CreateModel(
            name='BlockType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='routines/blocks/images')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cadence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('video_link', models.URLField(blank=True)),
                ('image', models.ImageField(upload_to='routines/exercises/images')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExerciseStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Exercise status',
                'verbose_name_plural': 'Exercise status',
            },
        ),
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='routines/goals/images')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='routines/levels/images')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='routines/muscle_group/images')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MuscleGroupType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='routines/muscle_group_type/images')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Restriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='routines/restrictions/images')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('warm_up', models.CharField(max_length=50)),
                ('cardio', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('pre_exhaustion', models.CharField(max_length=50)),
                ('activation', models.CharField(max_length=50)),
                ('rest_between_exercises', models.CharField(max_length=50)),
                ('cadence', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='routines.cadence')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoutineCustomerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Routine Customer status',
                'verbose_name_plural': 'Routine Customer status',
            },
        ),
        migrations.CreateModel(
            name='RoutineStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Routine status',
                'verbose_name_plural': 'Routine status',
            },
        ),
        migrations.CreateModel(
            name='RoutineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='routines/routine-type/images')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='routines/systems/images')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='routines/training/images')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrainingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='routines/training-method/images')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrainingMethodLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('translation', models.CharField(max_length=150)),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.language')),
                ('training_method', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='routines.trainingmethod')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='trainingmethod',
            name='lang',
            field=models.ManyToManyField(blank=True, through='routines.TrainingMethodLang', to='main.Language'),
        ),
        migrations.CreateModel(
            name='TrainingLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('translation', models.CharField(max_length=150)),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.language')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='routines.training')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='training',
            name='lang',
            field=models.ManyToManyField(blank=True, through='routines.TrainingLang', to='main.Language'),
        ),
        migrations.CreateModel(
            name='SystemLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('translation', models.CharField(max_length=150)),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.language')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='routines.system')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='system',
            name='lang',
            field=models.ManyToManyField(blank=True, through='routines.SystemLang', to='main.Language'),
        ),
        migrations.CreateModel(
            name='RoutineTypeLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('translation', models.CharField(max_length=150)),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.language')),
                ('routine_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='routines.routinetype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='routinetype',
            name='lang',
            field=models.ManyToManyField(blank=True, through='routines.RoutineTypeLang', to='main.Language'),
        ),
        migrations.CreateModel(
            name='RoutineStatusLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('translation', models.CharField(max_length=150)),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.language')),
                ('routine_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='routines.routinestatus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='routinestatus',
            name='lang',
            field=models.ManyToManyField(blank=True, through='routines.RoutineStatusLang', to='main.Language'),
        ),
        migrations.CreateModel(
            name='RoutineDaysBlocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('blocks', models.ManyToManyField(to='routines.Block')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='routines.day')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routines.routine')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoutineCustomerStatusLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('translation', models.CharField(max_length=150)),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.language')),
                ('routine_customer_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='routines.routinecustomerstatus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='routinecustomerstatus',
            name='lang',
            field=models.ManyToManyField(blank=True, through='routines.RoutineCustomerStatusLang', to='main.Language'),
        ),
        migrations.CreateModel(
            name='RoutineCustomers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('observation', models.TextField()),
                ('start_date', models.DateField(blank=True)),
                ('due_date', models.DateField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.customer')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='routines.routine')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='routines.routinecustomerstatus')),
            ],
            options={
                'verbose_name': 'Routine customers',
                'verbose_name_plural': 'Routine customers',
            },
        ),
        migrations.AddField(
            model_name='routine',
            name='days_of_week',
            field=models.ManyToManyField(blank=True, through='routines.RoutineDaysBlocks', to='routines.Day'),
        ),
        migrations.AddField(
            model_name='routine',
            name='goals',
            field=models.ManyToManyField(to='routines.Goal'),
        ),
        migrations.AddField(
            model_name='routine',
            name='lang',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.language'),
        ),
        migrations.AddField(
            model_name='routine',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='routines.level'),
        ),
        migrations.AddField(
            model_name='routine',
            name='restrictions',
            field=models.ManyToManyField(blank=True, to='routines.Restriction'),
        ),
        migrations.AddField(
            model_name='routine',
            name='routine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='routines.routinetype'),
        ),
        migrations.AddField(
            model_name='routine',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='routines.routinestatus'),
        ),
        migrations.AddField(
            model_name='routine',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='routines.system'),
        ),
        migrations.AddField(
            model_name='routine',
            name='training_method',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='routines.trainingmethod'),
        ),
        migrations.CreateModel(
            name='RestrictionLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('translation', models.CharField(max_length=150)),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.language')),
                ('restriction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='routines.restriction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='restriction',
            name='lang',
            field=models.ManyToManyField(blank=True, through='routines.RestrictionLang', to='main.Language'),
        ),
        migrations.CreateModel(
            name='MuscleGroupTypeLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('translation', models.CharField(max_length=150)),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.language')),
                ('muscle_group_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='routines.musclegrouptype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='musclegrouptype',
            name='lang',
            field=models.ManyToManyField(blank=True, through='routines.MuscleGroupTypeLang', to='main.Language'),
        ),
        migrations.CreateModel(
            name='MuscleGroupLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('translation', models.CharField(max_length=150)),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.language')),
                ('muscle_group', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='routines.musclegroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='musclegroup',
            name='lang',
            field=models.ManyToManyField(blank=True, through='routines.MuscleGroupLang', to='main.Language'),
        ),
        migrations.AddField(
            model_name='musclegroup',
            name='muscle_group_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='routines.musclegrouptype'),
        ),
        migrations.CreateModel(
            name='LevelLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('translation', models.CharField(max_length=150)),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.language')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='routines.level')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='level',
            name='lang',
            field=models.ManyToManyField(blank=True, through='routines.LevelLang', to='main.Language'),
        ),
        migrations.CreateModel(
            name='GoalLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('translation', models.CharField(max_length=150)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='routines.goal')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.language')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='goal',
            name='lang',
            field=models.ManyToManyField(blank=True, through='routines.GoalLang', to='main.Language'),
        ),
        migrations.CreateModel(
            name='ExerciseTypeLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('translation', models.CharField(max_length=150)),
                ('exercise_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='routines.exercisetype')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.language')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='exercisetype',
            name='lang',
            field=models.ManyToManyField(blank=True, through='routines.ExerciseTypeLang', to='main.Language'),
        ),
        migrations.AddField(
            model_name='exercisetype',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='routines.training'),
        ),
        migrations.CreateModel(
            name='ExerciseStatusLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('translation', models.CharField(max_length=150)),
                ('exercise_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='routines.exercisestatus')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.language')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='exercisestatus',
            name='lang',
            field=models.ManyToManyField(blank=True, through='routines.ExerciseStatusLang', to='main.Language'),
        ),
        migrations.CreateModel(
            name='ExerciseLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('translation', models.CharField(max_length=150)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='routines.exercise')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.language')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='lang',
            field=models.ManyToManyField(blank=True, through='routines.ExerciseLang', to='main.Language'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='routines.level'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscle_group',
            field=models.ManyToManyField(to='routines.MuscleGroup'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='routines.exercisestatus'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='routines.exercisetype'),
        ),
        migrations.CreateModel(
            name='DayLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('translation', models.CharField(max_length=150)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='routines.day')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.language')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='day',
            name='lang',
            field=models.ManyToManyField(blank=True, through='routines.DayLang', to='main.Language'),
        ),
        migrations.CreateModel(
            name='ContactTypeLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('translation', models.CharField(max_length=150)),
                ('contact_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='routines.contacttype')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.language')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='contacttype',
            name='lang',
            field=models.ManyToManyField(blank=True, through='routines.ContactTypeLang', to='main.Language'),
        ),
        migrations.CreateModel(
            name='CadenceLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('translation', models.CharField(max_length=150)),
                ('candence', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='routines.cadence')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.language')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cadence',
            name='lang',
            field=models.ManyToManyField(blank=True, through='routines.CadenceLang', to='main.Language'),
        ),
        migrations.CreateModel(
            name='BlockTypeLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('translation', models.CharField(max_length=150)),
                ('block_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='routines.blocktype')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.language')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='blocktype',
            name='lang',
            field=models.ManyToManyField(blank=True, through='routines.BlockTypeLang', to='main.Language'),
        ),
        migrations.CreateModel(
            name='BlockStatusLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('translation', models.CharField(max_length=150)),
                ('block_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='routines.blockstatus')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.language')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='blockstatus',
            name='lang',
            field=models.ManyToManyField(blank=True, through='routines.BlockStatusLang', to='main.Language'),
        ),
        migrations.CreateModel(
            name='BlockLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('translation', models.CharField(max_length=150)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='routines.block')),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.language')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlockExerciseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('serie', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('weight', models.CharField(max_length=10)),
                ('pause', models.CharField(max_length=10)),
                ('observation', models.TextField()),
                ('block', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='routines.block')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='routines.exercise')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='block',
            name='exercises',
            field=models.ManyToManyField(through='routines.BlockExerciseDetail', to='routines.Exercise'),
        ),
        migrations.AddField(
            model_name='block',
            name='lang',
            field=models.ManyToManyField(blank=True, through='routines.BlockLang', to='main.Language'),
        ),
        migrations.AddField(
            model_name='block',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='routines.blockstatus'),
        ),
        migrations.AddField(
            model_name='block',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='routines.blocktype'),
        ),
    ]
