# Generated by Django 4.2.11 on 2024-04-12 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.IntegerField(choices=[(1, 'En progreso'), (2, 'Lista'), (3, 'Pausada'), (4, 'Realizada')], default=1)),
                ('type', models.IntegerField(choices=[(13, 'Calentamiento'), (14, 'Post entrenamiento'), (15, 'Entrenamiento')])),
                ('description', models.TextField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='routines/exercises/images')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='routines/exercises/images')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='routines/exercises/images')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='routines/exercises/images')),
                ('muscle_group_type', models.IntegerField(choices=[(1, 'Tren superior'), (2, 'Brazos'), (3, 'Piernas'), (4, 'Core')], default=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Restriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='routines/exercises/images')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('status', models.IntegerField(choices=[(1, 'En progreso'), (2, 'Lista'), (3, 'Pausada'), (4, 'Realizada')], default=1)),
                ('description', models.TextField()),
                ('routine_type', models.IntegerField(choices=[(1, 'semanal'), (2, 'quincenal'), (3, 'trisemanal'), (4, 'Mensual'), (5, 'Trimestral')], default=4)),
                ('system', models.IntegerField(choices=[(1, 'Push Pull Legs Fuerza'), (2, 'Push Pull Legs Hipertrofia'), (3, 'Full Body Strength'), (4, 'Rutina dividida Hipertrofia')], default=4)),
                ('cadence', models.IntegerField(choices=[(1, 'Clasica 2-0-1')], default=1)),
                ('cardio', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('pre_exhaustion', models.IntegerField(choices=[(0, 'No'), (1, 'Si')], default=0)),
                ('activation', models.IntegerField(choices=[(0, 'No'), (1, 'Si')], default=0)),
                ('rest_between_exercises', models.CharField(max_length=50)),
                ('training_method', models.IntegerField(choices=[(1, 'Fuerza'), (2, 'Resistencia'), (3, 'Velocidad'), (4, 'Flexibilidad')], default=1)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='routines/exercises/images')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoutineTargetMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('min_age', models.IntegerField(blank=True, null=True)),
                ('max_age', models.IntegerField(blank=True, null=True)),
                ('customer_with_equipement', models.IntegerField(choices=[(0, 'No'), (1, 'Si')], default=0)),
                ('customer_train_at_home', models.IntegerField(choices=[(0, 'No'), (1, 'Si')], default=0)),
                ('customer_with_lack_space', models.IntegerField(choices=[(0, 'No'), (1, 'Si')], default=0)),
                ('customer_with_lack_time', models.IntegerField(choices=[(0, 'No'), (1, 'Si')], default=0)),
                ('goals', models.ManyToManyField(blank=True, to='routines.goal')),
                ('level', models.ManyToManyField(blank=True, to='routines.level')),
                ('routine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='routines.routine')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoutineDaysBlocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('blocks', models.ManyToManyField(blank=True, to='routines.block')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routines.day')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routines.routine')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoutineCustomers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'En progreso'), (2, 'Lista'), (3, 'Pausada'), (4, 'Realizada')], default=1)),
                ('observation', models.TextField()),
                ('start_date', models.DateField(blank=True)),
                ('due_date', models.DateField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.customer')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='routines.routine')),
            ],
            options={
                'verbose_name': 'Routine customers',
                'verbose_name_plural': 'Routine customers',
            },
        ),
        migrations.CreateModel(
            name='RoutineCustomerIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('started_on', models.DateTimeField()),
                ('finished_on', models.DateTimeField(auto_now_add=True)),
                ('welfare_scale', models.IntegerField(default=1)),
                ('effort_scale', models.IntegerField(default=1)),
                ('enjoyment_scale', models.IntegerField(default=1)),
                ('was_completed', models.IntegerField(choices=[(0, 'No'), (1, 'Si')], default=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.customer')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='routines.routine')),
            ],
            options={
                'verbose_name': 'Routine customers indicators',
                'verbose_name_plural': 'Routine customers indicators',
            },
        ),
        migrations.AddField(
            model_name='routine',
            name='days_of_week',
            field=models.ManyToManyField(blank=True, through='routines.RoutineDaysBlocks', to='routines.day'),
        ),
        migrations.AddField(
            model_name='routine',
            name='restrictions',
            field=models.ManyToManyField(blank=True, to='routines.restriction'),
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='routines/exercises/images')),
                ('description', models.TextField()),
                ('type', models.IntegerField(choices=[(1, 'Movilidad'), (2, 'Metabolicos'), (3, 'Lop'), (4, 'Pliometria'), (5, 'Compuestos'), (6, 'Estiramiento'), (7, 'Relajacion'), (8, 'Tren superior'), (9, 'Tren inferior'), (10, 'Zona media')], default=1)),
                ('status', models.IntegerField(choices=[(1, 'En progreso'), (2, 'Lista'), (3, 'Pausada'), (4, 'Realizada')], default=1)),
                ('video_link', models.URLField(blank=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='routines.level')),
                ('muscle_group', models.ManyToManyField(blank=True, to='routines.musclegroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlockExerciseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('serie', models.IntegerField(blank=True, null=True)),
                ('reps', models.IntegerField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.CharField(blank=True, max_length=10, null=True)),
                ('pause', models.CharField(blank=True, max_length=10, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('block', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='routines.block')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='routines.exercise')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='block',
            name='exercises',
            field=models.ManyToManyField(blank=True, through='routines.BlockExerciseDetail', to='routines.exercise'),
        ),
    ]
