# Generated by Django 4.2.11 on 2024-04-12 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('code', models.CharField(max_length=50)),
                ('encoding', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LanguageStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'language status',
                'verbose_name_plural': 'Language status',
            },
        ),
        migrations.CreateModel(
            name='LanguageStatusLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('translation', models.CharField(max_length=150)),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.language')),
                ('language_status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.languagestatus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='languagestatus',
            name='lang',
            field=models.ManyToManyField(blank=True, through='main.LanguageStatusLang', to='main.language'),
        ),
        migrations.AddField(
            model_name='language',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.languagestatus'),
        ),
    ]
