# Generated by Django 4.2.11 on 2024-04-12 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('value', models.FloatField(blank=True, max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('country', models.IntegerField(choices=[(1, 'Argentina'), (2, 'Brasil'), (3, 'Chile')], default=1)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, max_length=3, null=True)),
                ('height', models.FloatField(blank=True, max_length=3, null=True)),
                ('imc', models.FloatField(blank=True, max_length=3, null=True)),
                ('customer_with_equipement', models.IntegerField(choices=[(0, 'No'), (1, 'Si')], default=0)),
                ('customer_train_at_home', models.IntegerField(choices=[(0, 'No'), (1, 'Si')], default=0)),
                ('customer_with_lack_space', models.IntegerField(choices=[(0, 'No'), (1, 'Si')], default=0)),
                ('customer_with_lack_time', models.IntegerField(choices=[(0, 'No'), (1, 'Si')], default=0)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer_test_values', models.ManyToManyField(blank=True, to='customers.customertest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
