from django.contrib import admin
from ..models import *
from .exercises import *
from .routine_admin import *
from .block_admin import *
from ...customers.admin.customer_admin import *
from .day_admin import *
from .goal_admin import *
from .block_status_admin import *
from .restrictions_admin import *
from .routine_type_admin import *
from .exercise_status_admin import *
from .routine_status_admin import *
from .routine_customer_status_admin import *
from .muscle_group_admin import *
from .muscle_group_type_admin import *
from .level_admin import *
from .training_admin import *
from .cadence_admin import *
from .training_method_admin import *
from .system_admin import *